steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/smartlearning-api', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/smartlearning-api']

images:
- 'gcr.io/$PROJECT_ID/smartlearning-api'
